# Generated by Django 5.0.3 on 2024-03-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="empleados",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=254)),
                ("apellidos", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=254)),
                ("celular", models.BigIntegerField()),
                ("genero", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cargo_id", models.IntegerField(default=1)),
                ("estado_empleados_id", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "empleados",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pgr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "nombres_completos",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("correo", models.CharField(blank=True, max_length=45, null=True)),
                ("descripcion", models.CharField(blank=True, max_length=45, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pgr",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductosRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("precio", models.CharField(blank=True, max_length=250, null=True)),
                ("cantidad", models.CharField(blank=True, max_length=250, null=True)),
                ("imagen", models.CharField(blank=True, max_length=250, null=True)),
                ("create_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "productos_registro",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=45, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("update_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipo_producto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=254)),
                ("apellidos", models.CharField(max_length=255)),
                ("celular", models.BigIntegerField()),
                ("email", models.CharField(max_length=254)),
                ("direccion", models.CharField(max_length=254)),
                ("contrasena", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("estado_usuarios_id", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
    ]
