# Generated by Django 5.0.3 on 2024-03-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pqr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "nombres_completos",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("correo", models.CharField(blank=True, max_length=45, null=True)),
                ("descripcion", models.CharField(blank=True, max_length=45, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pqr",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductosRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("precio", models.CharField(blank=True, max_length=250, null=True)),
                ("cantidad", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="img/productos"),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "productos_registro",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=45, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipo_producto",
                "managed": False,
            },
        ),
    ]
