# Generated by Django 5.0.3 on 2024-03-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=254)),
                ('apellidos', models.CharField(max_length=255)),
                ('celular', models.BigIntegerField()),
                ('email', models.CharField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado_usuarios_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
