# Generated by Django 5.0.3 on 2024-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=45, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('celular', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=450, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('cargo_id', models.IntegerField()),
                ('estado_empleados_id', models.IntegerField()),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
    ]
