# Generated by Django 4.2.7 on 2024-03-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_delete_productos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                ("idcarousel", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("imagen_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "carousel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(blank=True, max_length=45, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("update_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipo_producto",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="productosregistro",
            options={"managed": True},
        ),
    ]
